FROM gradle:8.14.3-jdk17 AS build

WORKDIR /workspace

COPY . .

RUN ./gradlew :services:user-service:bootJar --no-daemon

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /workspace/services/user-service/build/libs/*.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]